### ISSUE TITLE
04-HTTPS-TLS - Let's Encrypt HTTP Challenge Lab

### ISSUE THREAD

**Issue by sw360cab** [56kcloud/traefik-training#3]
in the `traefik.http.yml` file in order to get `letsencrypt` folder mapped correctly to local filesystem from docker compose, the **certresolver** section should be changed this way:

```yaml
certificatesResolvers:
  myresolver:
    acme:
      email: your_email@example.com 
       storage: /letsencrypt/acme.json
      httpChallenge:
        entryPoint: web
```

`storage` key with value `acme.json` alone, would not map correctly the file.

Ref.
https://doc.traefik.io/traefik/user-guides/docker-compose/acme-http/#setup
